name: remote ssh command
on: [push]

jobs:
  build:
    name: build & run docker
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: docker shit
      uses: ./
      with:
        host: 103.175.219.128
        username: aimingds
        password: ${{ secrets.SSHPASS }}
        key: ${{ secrets.PRIVKEY }}
        port: 22
        script: |
         docker compose down
         docker compose build
         docker compose up -d
